package me.supcheg.javafile.facts.meta;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Marks a metamodel class generated by the `@Facts` processor (§5) and
/// records what it was generated from, so that a later compilation can reuse
/// it instead of generating its own (§6).
///
/// The processor finds the marker in the class files on the classpath, so
/// the retention is [RetentionPolicy#CLASS]. The name carries `Generated`
/// on purpose: JaCoCo leaves out of coverage the classes marked with an
/// annotation of class or runtime retention whose simple name contains
/// `Generated`.
@Documented
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface GeneratedMetamodel {

    /// The type the metamodel describes.
    ///
    /// @return the type, by class literal
    Class<?> of();

    /// The fingerprint of the type as it was when the metamodel was generated:
    /// a digest of everything the metamodel records about it. A metamodel is
    /// reused only if the fingerprint of the type on the current classpath
    /// is the same.
    ///
    /// @return the fingerprint
    String fingerprint();

    /// Whether the metamodel is complete: a token and a fact per member
    /// (`true`), or a token only, as generated for a type that only appears in
    /// the signature of a member (`false`).
    ///
    /// @return whether the metamodel is complete
    boolean complete();

    /// The [MetamodelFormat#VERSION] of the processor that generated the
    /// metamodel: which facts a complete metamodel has of a type is decided by
    /// the format, so a metamodel of another format is not reused, whatever
    /// its fingerprint.
    ///
    /// @return the format version
    int format();
}
