package me.supcheg.javafile.facts.meta;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Marks a class nested in a metamodel generated by the `@Facts` processor —
/// its `Data` and its `Canonical` — as part of the generated code.
///
/// [GeneratedMetamodel] marks the metamodel itself, but a tool that leaves
/// generated classes out of its report reads each class file for itself, and
/// a nested class does not inherit the annotation of the class it is in. The
/// name carries `Generated` for the same reason as that of
/// [GeneratedMetamodel]: JaCoCo leaves out of coverage the classes marked
/// with an annotation of class or runtime retention whose simple name
/// contains `Generated`. The processor does not read this annotation: a
/// metamodel is found by [GeneratedMetamodel] alone.
@Documented
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.TYPE)
public @interface GeneratedMetamodelPart {}
