package me.supcheg.javafile.facts.meta;

/// The version of the code the `@Facts` processor generates, and of the
/// `facts` API that code is written against.
///
/// The processor compares [#VERSION] with the one on the compile classpath of
/// the generator and fails on a mismatch: metamodels generated by one version
/// would not compile against the other. Any change to the generated code that
/// an older `facts` cannot compile — or that an older processor's output
/// cannot survive — raises it, and so does any change to which members of a
/// type get a fact: a metamodel records the version it was generated in
/// ([GeneratedMetamodel#format()]), and one of another version is not reused.
///
/// - 1: facts of members whose signatures are not generic.
/// - 2: metamodels of generic types with facts in terms of their type
///   parameters, facts of generic methods as factories that take a token per
///   type parameter, tokens of parameterized and raw types in signatures.
public final class MetamodelFormat {

    /// The current format version. A compile-time constant, so that the
    /// processor reads it from the class file with `getConstantValue()`
    /// without loading the class.
    public static final int VERSION = 2;

    private MetamodelFormat() {}
}
