package me.supcheg.javafile.facts.meta;

/// The version of the code the `@Facts` processor generates, and of the
/// `facts` API that code is written against.
///
/// The processor compares [#VERSION] with the one on the compile classpath of
/// the generator and fails on a mismatch: metamodels generated by one version
/// would not compile against the other. Any change to the generated code that
/// an older `facts` cannot compile — or that an older processor's output
/// cannot survive — raises it.
public final class MetamodelFormat {

    /// The current format version. A compile-time constant, so that the
    /// processor reads it from the class file with `getConstantValue()`
    /// without loading the class.
    public static final int VERSION = 1;

    private MetamodelFormat() {}
}
