package me.supcheg.javafile.facts.meta;

/// The version of the code the `@Facts` processor generates, and of the
/// `facts` API that code is written against.
///
/// The processor compares [#VERSION] with the one on the compile classpath of
/// the generator and fails on a mismatch: metamodels generated by one version
/// would not compile against the other. Any change to the generated code that
/// an older `facts` cannot compile — or that an older processor's output
/// cannot survive — raises it, and so does any change to which members of a
/// type get a fact: a metamodel records the version it was generated in
/// ([GeneratedMetamodel#format()]), and one of another version is not reused.
///
/// - 1: facts of members whose signatures are not generic.
/// - 2: metamodels of generic types with facts in terms of their type
///   parameters, facts of generic methods as factories that take a token per
///   type parameter, tokens of parameterized and raw types in signatures.
/// - 3: a fact says how the member declares each parameter that is a type
///   variable or an array of one, the method table lists `T[]` as an array of
///   the type argument, and lists the constructors.
/// - 4: a metamodel has the facts of the `public` members its type inherits
///   from supertypes that are not `public`, as members of the type; the
///   supertypes of a requested type have full metamodels of their own.
/// - 5: of several abstract methods of one signature a type adopts one only
///   if no `public` supertype declares the most specific; an adopted field
///   that is ambiguous in the type has no fact; a member a `public` supertype
///   without a full metamodel shares with the type stays a fact of the type;
///   `java.lang.Object` is a supertype of an interface too, so it gets a full
///   metamodel wherever an interface is asked for.
/// - 6: the canonical form of a type, and so its fingerprint, tells every
///   interface the type implements, not the parameterized ones alone: a
///   type that no longer implements one is another type to the check against
///   the target classpath.
/// - 7: the classes `Data` and `Canonical` nested in a metamodel are marked
///   [GeneratedMetamodelPart], an annotation an older `facts` does not have.
/// - 8: a class that can be extended has the facts of its `protected`
///   members, each held back in a `Protected`; the fact of a constructor a
///   subclass alone calls — of an abstract class, or `protected` — is a
///   `SuperCtorRefN`, which replaces `AbstractCtorRefN`; the shape of a type
///   tells the interfaces it implements, and a fact its access.
/// - 9: the full metamodel of a type a class can extend or implement tells
///   its heritage — every method and constructor such a class inherits or
///   could clash with —, as data of its shape and in its canonical form.
public final class MetamodelFormat {

    /// The current format version. A compile-time constant, so that the
    /// processor reads it from the class file with `getConstantValue()`
    /// without loading the class.
    public static final int VERSION = 9;

    private MetamodelFormat() {}
}
