/// The fact model of the typed semantic layer (§3): what types and members of
/// the target code exist, as values whose generic types javac checks when the
/// generator is compiled.
///
/// - Types: [me.supcheg.javafile.facts.TypeToken] and its sealed hierarchy.
///   The token kind decides what a type can be used for —
///   [me.supcheg.javafile.facts.InterfaceToken]s are implemented,
///   [me.supcheg.javafile.facts.OpenClassToken]s and
///   [me.supcheg.javafile.facts.AbstractClassToken]s are extended,
///   [me.supcheg.javafile.facts.ConcreteClassToken]s are instantiated,
///   [me.supcheg.javafile.facts.RefToken]s are type arguments.
/// - Members, one overload per fact (§3.2), arity 0 to 12:
///   `MethodRefN<O, R, A1..AN>` and `VoidMethodRefN<O, A1..AN>` (instance
///   methods), `StaticMethodRefN<R, A1..AN>` and `VoidStaticMethodRefN<A1..AN>`,
///   `CtorRefN<O, A1..AN>`, and the functional interface facts
///   `SamN<F, R, A1..AN>` / `VoidSamN<F, A1..AN>` that type lambdas (§6.4).
///   `void` methods are a family of their own, so a `void` call is never an
///   expression. The families are generated by
///   `me.supcheg.javafile.facts.codegen.FactsCodegen` — itself written on
///   `java-file-api-core` — and committed.
/// - Fields: [me.supcheg.javafile.facts.FieldRef] /
///   [me.supcheg.javafile.facts.MutableFieldRef] and their static
///   counterparts; only the mutable ones can be assigned.
/// - Runtime data generics cannot carry: throws-sets, overridability and
///   explicit type arguments ([me.supcheg.javafile.facts.MemberTraits]),
///   method tables, superclass chains, enum constants.
///
/// Every fact class has a static `introduce` factory: the single trusted point
/// where a fact source vouches for a fact. Generator code obtains facts from
/// metamodels (e.g. [me.supcheg.javafile.facts.jdk]), from the mirror source,
/// or from typed declarations — never from `introduce`.
@NullMarked
package me.supcheg.javafile.facts;

import org.jspecify.annotations.NullMarked;
