package me.supcheg.javafile.facts;

import java.lang.constant.ClassDesc;
import java.util.function.Supplier;
import java.util.regex.Pattern;

/// Who vouches for a [TypeShape], which decides whether the shape is checked
/// against the classpath of the target code.
///
/// - [Metamodel] — generated by the `@Facts` processor from the classpath the
///   generator was compiled against; checked against the target classpath,
///   since the two may differ.
/// - [#MIRROR] — read from the target code itself through
///   `javax.lang.model` by the mirror source; nothing to check.
/// - [#UNSAFE] — vouched for by hand through the factories of [UnsafeFacts]
///   that take no origin; unchecked, like every other hand-made fact.
/// - [#BUILTIN] — made by this module for the types it knows by definition,
///   the boxes of [PrimitiveToken#boxed()]; unchecked.
///
/// Only [Metamodel] can be claimed by a caller: a shape of any other origin
/// is made by the module that owns that origin, so a shape cannot pass for
/// a built-in one.
public sealed interface ShapeOrigin
        permits ShapeOrigin.Metamodel, ShapeOrigin.Mirror, ShapeOrigin.Unsafe, ShapeOrigin.Builtin {

    /// Read from the target code by the mirror source.
    Mirror MIRROR = new Mirror();

    /// Vouched for by hand through [UnsafeFacts].
    Unsafe UNSAFE = new Unsafe();

    /// Made by this module for a type it knows by definition.
    Builtin BUILTIN = new Builtin();

    /// A shape generated by the `@Facts` processor.
    ///
    /// @param metamodel the generated metamodel class
    /// @param fingerprint the SHA-256 of the canonical form of the type, as 64 lowercase hex digits
    /// @param canonical supplies the canonical form, loaded only when the fingerprint does not match the target
    record Metamodel(ClassDesc metamodel, String fingerprint, Supplier<String> canonical) implements ShapeOrigin {
        private static final Pattern SHA_256 = Pattern.compile("[0-9a-f]{64}");

        /// @throws IllegalArgumentException if `metamodel` is not a class or
        ///                                  `fingerprint` is not a SHA-256 in lowercase hex
        public Metamodel {
            if (!metamodel.isClassOrInterface()) {
                throw new IllegalArgumentException("a metamodel is a class, got " + metamodel.descriptorString());
            }
            if (!SHA_256.matcher(fingerprint).matches()) {
                throw new IllegalArgumentException(
                        "a fingerprint is a SHA-256 as 64 lowercase hex digits, got \"" + fingerprint + "\"");
            }
        }

        @Override
        public String toString() {
            return "metamodel " + TypeNames.describe(metamodel) + " (" + fingerprint + ")";
        }
    }

    /// The origin of a shape read from the target code, [#MIRROR].
    final class Mirror implements ShapeOrigin {
        private Mirror() {}

        @Override
        public String toString() {
            return "mirror";
        }
    }

    /// The origin of a shape vouched for by hand, [#UNSAFE].
    final class Unsafe implements ShapeOrigin {
        private Unsafe() {}

        @Override
        public String toString() {
            return "unsafe";
        }
    }

    /// The origin of a shape this module makes, [#BUILTIN].
    final class Builtin implements ShapeOrigin {
        private Builtin() {}

        @Override
        public String toString() {
            return "builtin";
        }
    }
}
