package me.supcheg.javafile.facts;

import java.util.List;

/// What a [TargetReader] finds of the type of a metamodel on the target
/// classpath, compared with what the metamodel was generated from (§5).
///
/// - [Unchanged] — the type is the one the metamodel was generated from:
///   every fact of the metamodel holds, and so does its [TypeShape].
/// - [Changed] — the type is another, yet every fact of the metamodel
///   holds of it and the data of its shape is the same, but for what was
///   added: members, and interfaces the type implements. The method table
///   is that of the target, so an overload added there — by the type or by
///   an interface it has got — is a candidate lowering knows of; an added
///   interface takes nothing away, as a value of the type is still one of
///   every supertype the metamodel tells.
/// - [Mismatched] — a fact of the metamodel does not hold of the type, the
///   data of its shape differs, a supertype the metamodel tells is not one
///   of the type, or the type is not there: the metamodel is of no use to
///   this compilation.
public sealed interface TargetType permits TargetType.Holds, TargetType.Mismatched {

    /// The type is the one the metamodel was generated from.
    Unchanged UNCHANGED = new Unchanged();

    /// The metamodel holds on the target classpath: [Unchanged] or
    /// [Changed].
    sealed interface Holds extends TargetType permits Unchanged, Changed {}

    /// The type is the one the metamodel was generated from, [#UNCHANGED]:
    /// their fingerprints are equal.
    record Unchanged() implements Holds {}

    /// The type differs from the one the metamodel was generated from in
    /// what no fact of the metamodel tells.
    ///
    /// @param methods the methods of the type on the target classpath, in terms of its type parameters,
    ///                which are those of the shape
    /// @param heritage the heritage of the type on the target classpath, which stands for that of a shape
    ///                 that tells one; [Heritage#UNTOLD] of a type that cannot be extended or implemented
    record Changed(MethodTableTemplate methods, Heritage heritage) implements Holds {}

    /// The metamodel does not hold of the target classpath.
    ///
    /// @param differences what differs, in the order they are to be told in
    record Mismatched(List<Difference> differences) implements TargetType {

        /// @throws IllegalArgumentException if there is no difference
        public Mismatched {
            differences = List.copyOf(differences);
            if (differences.isEmpty()) {
                throw new IllegalArgumentException("a mismatch has a difference");
            }
        }
    }

    /// One thing a metamodel says that the target classpath does not.
    sealed interface Difference
            permits Difference.Absent,
                    Difference.OtherFormat,
                    Difference.MissingFact,
                    Difference.ChangedFact,
                    Difference.ChangedData,
                    Difference.MissingInterface,
                    Difference.ChangedSupertype {

        /// The lines of a message that tell the difference, the first of
        /// them naming it.
        ///
        /// @return the lines, without indentation
        List<String> lines();

        /// The type cannot be read off the target classpath: it is not
        /// there, code of another package cannot name it, or it mentions a
        /// type that is not there.
        ///
        /// @param reason why, as a sentence about the type
        record Absent(String reason) implements Difference {
            @Override
            public List<String> lines() {
                return List.of(reason);
            }
        }

        /// The metamodel records its type in another format than the one
        /// the target classpath is read in: it was generated by another
        /// version of the processor, and nothing of it can be compared.
        ///
        /// @param generated the format of the metamodel, the first line of its canonical form
        /// @param target the format the target classpath is read in
        record OtherFormat(String generated, String target) implements Difference {
            @Override
            public List<String> lines() {
                return List.of("format: generated as " + generated + ", the target is read as " + target);
            }
        }

        /// A member the metamodel has a fact of is not a member of the
        /// type.
        ///
        /// @param fact the member, as the canonical form of the metamodel tells it
        /// @param similar the members of that kind and name the type has, as its canonical form tells them
        record MissingFact(String fact, List<String> similar) implements Difference {
            public MissingFact {
                similar = List.copyOf(similar);
            }

            @Override
            public List<String> lines() {
                return similar.isEmpty()
                        ? List.of("missing: " + fact)
                        : List.of("missing: " + fact, "  similar: " + String.join("; ", similar));
            }
        }

        /// A member the metamodel has a fact of is declared otherwise by
        /// the type: another parameter, result, exception, modifier or
        /// constant value.
        ///
        /// @param fact the member, as the canonical form of the metamodel tells it
        /// @param found the member of the type, as its canonical form tells it
        record ChangedFact(String fact, String found) implements Difference {
            @Override
            public List<String> lines() {
                return List.of("changed: " + fact, "  found: " + found);
            }
        }

        /// Data of the [TypeShape] that is to be the same differs: the kind
        /// of the type, its type parameters, superclasses or enum constants.
        ///
        /// @param what which data, as the canonical form names it
        /// @param generated the data of the metamodel
        /// @param target the data of the type on the target classpath
        record ChangedData(String what, String generated, String target) implements Difference {
            @Override
            public List<String> lines() {
                return List.of("changed: " + what, "  generated against: " + generated, "  target: " + target);
            }
        }

        /// An interface the metamodel tells the type implements or extends,
        /// itself or through a supertype, is not one of the type: an
        /// expression of the type the compiler of the generator took for
        /// one of the interface is none here.
        ///
        /// @param name the interface, by binary name
        record MissingInterface(String name) implements Difference {
            @Override
            public List<String> lines() {
                return List.of("missing: interface " + name);
            }
        }

        /// A parameterized supertype the metamodel tells is a supertype of
        /// the type with other type arguments, or with none: `Comparable<String>`
        /// where the type is a `Comparable<Object>`.
        ///
        /// @param supertype the supertype, as the canonical form of the metamodel tells it
        /// @param found the supertype of that class or interface the type has, as its canonical form tells
        ///              it; the name alone if the type has it without type arguments
        record ChangedSupertype(String supertype, String found) implements Difference {
            @Override
            public List<String> lines() {
                return List.of("changed: supertype " + supertype, "  found: " + found);
            }
        }
    }
}
