package me.supcheg.javafile.facts;

import me.supcheg.javafile.facts.source.MemberResolver;
import me.supcheg.javafile.type.ClassOrInterfaceTypeRef;
import me.supcheg.javafile.type.ClassTypeRef;
import me.supcheg.javafile.type.TypeVarRef;

import java.lang.constant.ClassDesc;
import java.util.List;
import java.util.Optional;

/// The single trusted point where facts are introduced (§3.1): every token
/// and member fact that is not derived from another fact is created here and
/// nowhere else.
///
/// Each factory vouches for a fact without checking it — that `String` is a
/// final class, that it has a method `int length()`. A wrong fact makes the
/// typed layer build code that does not compile, which is exactly what the
/// layer exists to rule out; so the constructors of the fact classes are not
/// public, and this class is the only way around them. Its name puts every
/// use under the audit of the guarantee (§1): `grep Unsafe` over the
/// non-generated sources of a generator lists every place that vouches for a
/// fact by hand.
///
/// Legitimate users are the fact sources of this project:
///
/// - metamodels, generated by the `@Facts` processor and marked
///   `@Generated` (the hand-written `me.supcheg.javafile.facts.jdk` stands in
///   for its output and is marked the same way);
/// - the mirror source of `java-file-api-lang-model`, which checks every fact
///   against `javax.lang.model` in a [MemberResolver] and wraps it with
///   [#factSource(DeclaredToken, MemberResolver)];
/// - the typed declarations of `java-file-api-typed`, where declaring a
///   member is introducing its fact.
///
/// Facts derived from other facts need no trust and stay public where they
/// are: [ArrayToken#of(RefToken)], [PrimitiveToken#boxed()],
/// [EnumToken#constant(String)].
///
/// The member factories of the arity families — `method`, `voidMethod`,
/// `staticMethod`, `voidStaticMethod`, `ctor`, `abstractCtor`, `sam`,
/// `voidSam`, each for arity 0 to 12 — are generated and inherited from a
/// package-private superclass; call them as `UnsafeFacts.method(...)`.
///
/// A constructor fact comes in two families (§3.1): `ctor` needs a
/// [ConcreteClassToken] and gives a `CtorRefN`, the only constructor fact
/// `new_` accepts; `abstractCtor` needs an [AbstractClassToken] and gives an
/// `AbstractCtorRefN`, usable only to call the constructor from a subclass.
public final class UnsafeFacts extends InvocableFactories {
    private UnsafeFacts() {}

    /// Vouches that a final class, a record included, exists.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> FinalClassToken<T> finalClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, MethodTable methods) {
        return new FinalClassToken<>(typeRef, superclasses, methods);
    }

    /// Vouches that a class that is neither abstract nor final exists.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> OpenClassToken<T> openClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, MethodTable methods) {
        return new OpenClassToken<>(typeRef, superclasses, methods);
    }

    /// Vouches that an abstract class exists.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> AbstractClassToken<T> abstractClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, MethodTable methods) {
        return new AbstractClassToken<>(typeRef, superclasses, methods);
    }

    /// Vouches that an interface exists.
    ///
    /// @param typeRef the interface type, plain or parameterized
    /// @param methods the interface's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> InterfaceToken<T> interfaceToken(ClassOrInterfaceTypeRef typeRef, MethodTable methods) {
        return new InterfaceToken<>(typeRef, methods);
    }

    /// Vouches that an enum exists with the given constants.
    ///
    /// @param typeRef the enum type
    /// @param constants the enum's constant names, in declaration order
    /// @param methods the enum's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    public static <T> EnumToken<T> enumToken(ClassTypeRef typeRef, List<String> constants, MethodTable methods) {
        return new EnumToken<>(typeRef, constants, methods);
    }

    /// Vouches that a type variable is in scope.
    ///
    /// @param typeRef the type variable
    /// @param erasure the erasure of its leftmost bound, `java.lang.Object` for none
    /// @param <T> the type variable the token stands for
    /// @return the token
    public static <T> TypeVarToken<T> typeVarToken(TypeVarRef typeRef, ClassDesc erasure) {
        return new TypeVarToken<>(typeRef, erasure);
    }

    /// Vouches that a type has a `final` instance field.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type, as a member of `owner`
    /// @param <O> the owner type
    /// @param <T> the field type
    /// @return the fact
    public static <O, T> FieldRef<O, T> field(DeclaredToken<O> owner, String name, TypeToken<T> type) {
        return new FieldRef<>(owner, name, type);
    }

    /// Vouches that a type has a non-`final` instance field.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type, as a member of `owner`
    /// @param <O> the owner type
    /// @param <T> the field type
    /// @return the fact
    public static <O, T> MutableFieldRef<O, T> mutableField(DeclaredToken<O> owner, String name, TypeToken<T> type) {
        return new MutableFieldRef<>(owner, name, type);
    }

    /// Vouches that a type has a `final` static field that is not a constant
    /// variable.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type
    /// @param <T> the field type
    /// @return the fact
    public static <T> StaticFieldRef<T> staticField(DeclaredToken<?> owner, String name, TypeToken<T> type) {
        return new StaticFieldRef<>(owner, name, type, Optional.empty());
    }

    /// Vouches that a type has a primitive constant variable: a `final`
    /// static field initialized with a constant expression.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type
    /// @param value the constant value, boxed
    /// @param <P> the marker of the field type
    /// @param <B> the box of the field type
    /// @return the fact
    public static <P, B> StaticFieldRef<P> constantField(
            DeclaredToken<?> owner, String name, PrimitiveToken<P, B, ?> type, B value) {
        return new StaticFieldRef<>(owner, name, type, Optional.of(value));
    }

    /// Vouches that a type has a `String` constant variable.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the `String` token
    /// @param value the constant value
    /// @return the fact
    /// @throws IllegalArgumentException if `type` is not the token of `String`
    public static StaticFieldRef<String> constantField(
            DeclaredToken<?> owner, String name, DeclaredToken<String> type, String value) {
        return new StaticFieldRef<>(owner, name, type, Optional.of(value));
    }

    /// Vouches that a type has a non-`final` static field.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type
    /// @param <T> the field type
    /// @return the fact
    public static <T> MutableStaticFieldRef<T> mutableStaticField(
            DeclaredToken<?> owner, String name, TypeToken<T> type) {
        return new MutableStaticFieldRef<>(owner, name, type);
    }

    /// Vouches for a runtime fact source (§3.8): every member `resolver`
    /// proves becomes a fact of `token`.
    ///
    /// [FactSource] is final and has no public constructor, so a source that
    /// proves everything cannot be written without this call.
    ///
    /// @param token the type whose members are looked up
    /// @param resolver proves members of `token` or fails fast
    /// @param <O> the type
    /// @return the source
    public static <O> FactSource<O> factSource(DeclaredToken<O> token, MemberResolver resolver) {
        return new FactSource<>(token, resolver);
    }
}
