package me.supcheg.javafile.facts;

import me.supcheg.javafile.facts.source.MemberResolver;
import me.supcheg.javafile.type.ClassOrInterfaceTypeRef;
import me.supcheg.javafile.type.ClassTypeRef;
import me.supcheg.javafile.type.TypeParam;
import me.supcheg.javafile.type.TypeVarRef;

import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

/// The single trusted point where facts are introduced (§3.1): every token
/// and member fact that is not derived from another fact is created here and
/// nowhere else.
///
/// Each factory vouches for a fact without checking it — that `String` is a
/// final class, that it has a method `int length()`. A wrong fact makes the
/// typed layer build code that does not compile, which is exactly what the
/// layer exists to rule out; so the constructors of the fact classes are not
/// public, and this class is the only way around them. Its name puts every
/// use under the audit of the guarantee (§1): `grep Unsafe` over the
/// non-generated sources of a generator lists every place that vouches for a
/// fact by hand.
///
/// Legitimate users are the fact sources of this project:
///
/// - metamodels, generated by the `@Facts` processor and marked
///   `@Generated` (the hand-written `me.supcheg.javafile.facts.jdk` stands in
///   for its output and is marked the same way);
/// - the mirror source of `java-file-api-lang-model`, which checks every fact
///   against `javax.lang.model` in a [MemberResolver] and wraps it with
///   [#factSource(DeclaredToken, MemberResolver)];
/// - the typed declarations of `java-file-api-typed`, where declaring a
///   member is introducing its fact.
///
/// A declared token is a [TypeShape] — the data of a type apart from its
/// type arguments — applied to type arguments. A shape is made by
/// [#shape(ShapeOrigin.Metamodel, DeclaredKind, ClassDesc, List, List, Supertypes, MethodTableTemplate, List, boolean)]
/// (generated metamodels, origin [ShapeOrigin.Metamodel]) or by the same
/// factory without an origin (by hand, [ShapeOrigin#UNSAFE]); a token of it
/// by the factory of its kind, e.g.
/// [#interfaceToken(TypeShape, TokenArg...)]. The factories that take a type
/// reference instead of a shape make a shape of origin [ShapeOrigin#UNSAFE]
/// for that one token.
///
/// Facts derived from other facts need no trust and stay public where they
/// are: [ArrayToken#of(RefToken)], [PrimitiveToken#boxed()],
/// [EnumToken#constant(String)].
///
/// The member factories of the arity families — `method`, `voidMethod`,
/// `staticMethod`, `voidStaticMethod`, `ctor`, `abstractCtor`, `sam`,
/// `voidSam`, each for arity 0 to 12 — are generated and inherited from a
/// package-private superclass; call them as `UnsafeFacts.method(...)`.
///
/// A constructor fact comes in two families (§3.1): `ctor` needs a
/// [ConcreteClassToken] and gives a `CtorRefN`, the only constructor fact
/// `new_` accepts; `abstractCtor` needs an [AbstractClassToken] and gives an
/// `AbstractCtorRefN`, usable only to call the constructor from a subclass.
public final class UnsafeFacts extends InvocableFactories {
    private UnsafeFacts() {}

    /// Vouches for the shape of a type, as a metamodel generated by the
    /// `@Facts` processor does (§5): the shape is checked against the
    /// target classpath, see [ShapeOrigin.Metamodel].
    ///
    /// @param origin the generated metamodel and the fingerprint of the type
    /// @param kind the kind of the type, which decides its token class
    /// @param desc the class or interface
    /// @param typeParameters the type parameters with their bounds, see [TypeShape#typeParameters()]
    /// @param superclasses the erased superclass chain, see [TypeShape#superclasses()]
    /// @param supertypes the parameterized supertypes, see [TypeShape#supertypes()]
    /// @param methods the methods, instance and `static`, declared and inherited, see [TypeShape#methods()]
    /// @param enumConstants the enum constants, see [TypeShape#enumConstants()]
    /// @param sealed whether the type is `sealed`
    /// @param <K> the kind of the type
    /// @return the shape
    /// @throws IllegalArgumentException if the data is inconsistent, see [TypeShape]
    public static <K extends DeclaredKind> TypeShape<K> shape(
            ShapeOrigin.Metamodel origin,
            K kind,
            ClassDesc desc,
            List<TypeParam> typeParameters,
            List<ClassDesc> superclasses,
            Supertypes supertypes,
            MethodTableTemplate methods,
            List<String> enumConstants,
            boolean sealed) {
        return new TypeShape<>(
                origin, kind, desc, typeParameters, superclasses, supertypes, methods, enumConstants, sealed);
    }

    /// Vouches for the shape of a type by hand: the shape is of origin
    /// [ShapeOrigin#UNSAFE] and is never checked against the target
    /// classpath.
    ///
    /// @param kind the kind of the type, which decides its token class
    /// @param desc the class or interface
    /// @param typeParameters the type parameters with their bounds, see [TypeShape#typeParameters()]
    /// @param superclasses the erased superclass chain, see [TypeShape#superclasses()]
    /// @param supertypes the parameterized supertypes, see [TypeShape#supertypes()]
    /// @param methods the methods, instance and `static`, declared and inherited, see [TypeShape#methods()]
    /// @param enumConstants the enum constants, see [TypeShape#enumConstants()]
    /// @param sealed whether the type is `sealed`
    /// @param <K> the kind of the type
    /// @return the shape
    /// @throws IllegalArgumentException if the data is inconsistent, see [TypeShape]
    public static <K extends DeclaredKind> TypeShape<K> shape(
            K kind,
            ClassDesc desc,
            List<TypeParam> typeParameters,
            List<ClassDesc> superclasses,
            Supertypes supertypes,
            MethodTableTemplate methods,
            List<String> enumConstants,
            boolean sealed) {
        return new TypeShape<>(
                ShapeOrigin.UNSAFE,
                kind,
                desc,
                typeParameters,
                superclasses,
                supertypes,
                methods,
                enumConstants,
                sealed);
    }

    /// The token of a final class, a record included: `shape` applied to
    /// `args`.
    ///
    /// @param shape the shape of the class
    /// @param args one type argument per type parameter of `shape`, or none for the raw type
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `args` is neither empty nor one per type parameter
    public static <T> FinalClassToken<T> finalClassToken(TypeShape<DeclaredKind.FinalClass> shape, TokenArg... args) {
        return new FinalClassToken<>(shape, List.of(args));
    }

    /// The token of a class that is neither abstract nor final: `shape`
    /// applied to `args`.
    ///
    /// @param shape the shape of the class
    /// @param args one type argument per type parameter of `shape`, or none for the raw type
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `args` is neither empty nor one per type parameter
    public static <T> OpenClassToken<T> openClassToken(TypeShape<DeclaredKind.OpenClass> shape, TokenArg... args) {
        return new OpenClassToken<>(shape, List.of(args));
    }

    /// The token of an abstract class: `shape` applied to `args`.
    ///
    /// @param shape the shape of the class
    /// @param args one type argument per type parameter of `shape`, or none for the raw type
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `args` is neither empty nor one per type parameter
    public static <T> AbstractClassToken<T> abstractClassToken(
            TypeShape<DeclaredKind.AbstractClass> shape, TokenArg... args) {
        return new AbstractClassToken<>(shape, List.of(args));
    }

    /// The token of an interface: `shape` applied to `args`.
    ///
    /// @param shape the shape of the interface
    /// @param args one type argument per type parameter of `shape`, or none for the raw type
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `args` is neither empty nor one per type parameter
    public static <T> InterfaceToken<T> interfaceToken(TypeShape<DeclaredKind.Interface> shape, TokenArg... args) {
        return new InterfaceToken<>(shape, List.of(args));
    }

    /// The token of an enum class.
    ///
    /// @param shape the shape of the enum
    /// @param <T> the Java type the token stands for
    /// @return the token
    public static <T> EnumToken<T> enumToken(TypeShape<DeclaredKind.EnumClass> shape) {
        return new EnumToken<>(shape);
    }

    /// Vouches that a final class, a record included, exists.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> FinalClassToken<T> finalClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, MethodTable methods) {
        return finalClassToken(typeRef, superclasses, Supertypes.NONE, methods);
    }

    /// Vouches that a generic final class exists, with its parameterized
    /// supertypes.
    ///
    /// @param typeRef the class type, parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param supertypes the parameterized supertypes of the generic class, see [DeclaredToken#supertypes()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable, or its
    ///                                  type arguments do not match the type parameters of `supertypes`
    public static <T> FinalClassToken<T> finalClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, Supertypes supertypes, MethodTable methods) {
        TypeShape<DeclaredKind.FinalClass> shape =
                TypeShape.unsafe(DeclaredKind.FINAL_CLASS, typeRef, superclasses, supertypes, () -> methods, List.of());
        return new FinalClassToken<>(shape, typeRef, shape.boundErasures());
    }

    /// Vouches that a final class exists whose instance methods are known
    /// only later: the class being declared by a typed declaration (§6.5),
    /// whose method table is complete once its declaration is. `methods` is
    /// asked until it answers once, and may throw while the table is not
    /// known yet.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods supplies the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> FinalClassToken<T> finalClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, Supplier<MethodTable> methods) {
        TypeShape<DeclaredKind.FinalClass> shape =
                TypeShape.unsafe(DeclaredKind.FINAL_CLASS, typeRef, superclasses, Supertypes.NONE, methods, List.of());
        return new FinalClassToken<>(shape, typeRef, shape.boundErasures());
    }

    /// Vouches that a class that is neither abstract nor final exists.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> OpenClassToken<T> openClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, MethodTable methods) {
        return openClassToken(typeRef, superclasses, Supertypes.NONE, methods);
    }

    /// Vouches that a generic class that is neither abstract nor final
    /// exists, with its parameterized supertypes.
    ///
    /// @param typeRef the class type, parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param supertypes the parameterized supertypes of the generic class, see [DeclaredToken#supertypes()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable, or its
    ///                                  type arguments do not match the type parameters of `supertypes`
    public static <T> OpenClassToken<T> openClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, Supertypes supertypes, MethodTable methods) {
        TypeShape<DeclaredKind.OpenClass> shape =
                TypeShape.unsafe(DeclaredKind.OPEN_CLASS, typeRef, superclasses, supertypes, () -> methods, List.of());
        return new OpenClassToken<>(shape, typeRef, shape.boundErasures());
    }

    /// Vouches that an abstract class exists.
    ///
    /// @param typeRef the class type, plain or parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> AbstractClassToken<T> abstractClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, MethodTable methods) {
        return abstractClassToken(typeRef, superclasses, Supertypes.NONE, methods);
    }

    /// Vouches that a generic abstract class exists, with its parameterized
    /// supertypes.
    ///
    /// @param typeRef the class type, parameterized
    /// @param superclasses the erased superclass chain, see [ClassToken#superclasses()]
    /// @param supertypes the parameterized supertypes of the generic class, see [DeclaredToken#supertypes()]
    /// @param methods the class's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable, or its
    ///                                  type arguments do not match the type parameters of `supertypes`
    public static <T> AbstractClassToken<T> abstractClassToken(
            ClassOrInterfaceTypeRef typeRef, List<ClassDesc> superclasses, Supertypes supertypes, MethodTable methods) {
        TypeShape<DeclaredKind.AbstractClass> shape = TypeShape.unsafe(
                DeclaredKind.ABSTRACT_CLASS, typeRef, superclasses, supertypes, () -> methods, List.of());
        return new AbstractClassToken<>(shape, typeRef, shape.boundErasures());
    }

    /// Vouches that an interface exists.
    ///
    /// @param typeRef the interface type, plain or parameterized
    /// @param methods the interface's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable
    public static <T> InterfaceToken<T> interfaceToken(ClassOrInterfaceTypeRef typeRef, MethodTable methods) {
        return interfaceToken(typeRef, Supertypes.NONE, methods);
    }

    /// Vouches that a generic interface exists, with its parameterized
    /// supertypes.
    ///
    /// @param typeRef the interface type, parameterized
    /// @param supertypes the parameterized supertypes of the generic interface, see [DeclaredToken#supertypes()]
    /// @param methods the interface's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    /// @throws IllegalArgumentException if `typeRef` is a type variable, or its
    ///                                  type arguments do not match the type parameters of `supertypes`
    public static <T> InterfaceToken<T> interfaceToken(
            ClassOrInterfaceTypeRef typeRef, Supertypes supertypes, MethodTable methods) {
        TypeShape<DeclaredKind.Interface> shape =
                TypeShape.unsafe(DeclaredKind.INTERFACE, typeRef, List.of(), supertypes, () -> methods, List.of());
        return new InterfaceToken<>(shape, typeRef, shape.boundErasures());
    }

    /// Vouches that an enum exists with the given constants.
    ///
    /// @param typeRef the enum type
    /// @param constants the enum's constant names, in declaration order
    /// @param methods the enum's instance methods, declared and inherited
    /// @param <T> the Java type the token stands for
    /// @return the token
    public static <T> EnumToken<T> enumToken(ClassTypeRef typeRef, List<String> constants, MethodTable methods) {
        return new EnumToken<>(TypeShape.unsafe(
                DeclaredKind.ENUM_CLASS,
                typeRef,
                List.of(ClassDesc.of("java.lang.Enum"), ConstantDescs.CD_Object),
                Supertypes.NONE,
                () -> methods,
                constants));
    }

    /// Vouches that a type variable is in scope.
    ///
    /// @param typeRef the type variable
    /// @param erasure the erasure of its leftmost bound, `java.lang.Object` for none
    /// @param <T> the type variable the token stands for
    /// @return the token
    public static <T> TypeVarToken<T> typeVarToken(TypeVarRef typeRef, ClassDesc erasure) {
        return new TypeVarToken<>(typeRef, erasure);
    }

    /// Vouches for how a method or constructor declares a parameter: by a
    /// type variable, or an array of one, that `token` stands for in the
    /// fact.
    ///
    /// - A parameter declared `T`, `T[]` or `T...` for the type parameter
    ///   `T` of the owner's type is [MethodTableTemplate.Var]: `add(E)` of
    ///   `List<E>` is `param(e, Param.var(0))`.
    /// - A parameter declared by a type parameter of the method itself is
    ///   [MethodTableTemplate.Fixed], the erasure of the declaration (JLS
    ///   4.6): `<T> of(T)` is `param(t, Param.fixed(CD_Object))`.
    ///
    /// Any other parameter is declared as its token erases, and is the token
    /// itself.
    ///
    /// @param token the type of the parameter in the fact
    /// @param declared the parameter in the signature the member declares
    /// @param <T> the type of the parameter in the fact
    /// @return the parameter
    public static <T> FactParam<T> param(TypeToken<T> token, MethodTableTemplate.Param declared) {
        return new DeclaredParam<>(token, declared);
    }

    /// Vouches that a type has a `final` instance field.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type, as a member of `owner`
    /// @param <O> the owner type
    /// @param <T> the field type
    /// @return the fact
    public static <O, T> FieldRef<O, T> field(DeclaredToken<O> owner, String name, TypeToken<T> type) {
        return new FieldRef<>(owner, name, type);
    }

    /// Vouches that a type has a non-`final` instance field.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type, as a member of `owner`
    /// @param <O> the owner type
    /// @param <T> the field type
    /// @return the fact
    public static <O, T> MutableFieldRef<O, T> mutableField(DeclaredToken<O> owner, String name, TypeToken<T> type) {
        return new MutableFieldRef<>(owner, name, type);
    }

    /// Vouches that a type has a `final` static field that is not a constant
    /// variable.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type
    /// @param <T> the field type
    /// @return the fact
    public static <T> StaticFieldRef<T> staticField(DeclaredToken<?> owner, String name, TypeToken<T> type) {
        return new StaticFieldRef<>(owner, name, type, Optional.empty());
    }

    /// Vouches that a type has a primitive constant variable: a `final`
    /// static field initialized with a constant expression.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type
    /// @param value the constant value, boxed
    /// @param <P> the marker of the field type
    /// @param <B> the box of the field type
    /// @return the fact
    public static <P, B> StaticFieldRef<P> constantField(
            DeclaredToken<?> owner, String name, PrimitiveToken<P, B, ?> type, B value) {
        return new StaticFieldRef<>(owner, name, type, Optional.of(value));
    }

    /// Vouches that a type has a `String` constant variable.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the `String` token
    /// @param value the constant value
    /// @return the fact
    /// @throws IllegalArgumentException if `type` is not the token of `String`
    public static StaticFieldRef<String> constantField(
            DeclaredToken<?> owner, String name, DeclaredToken<String> type, String value) {
        return new StaticFieldRef<>(owner, name, type, Optional.of(value));
    }

    /// Vouches that a type has a non-`final` static field.
    ///
    /// @param owner the type owning the field
    /// @param name the field name
    /// @param type the field type
    /// @param <T> the field type
    /// @return the fact
    public static <T> MutableStaticFieldRef<T> mutableStaticField(
            DeclaredToken<?> owner, String name, TypeToken<T> type) {
        return new MutableStaticFieldRef<>(owner, name, type);
    }

    /// Vouches for a reader of the target classpath (§5): what `reader`
    /// answers decides which metamodels the typed layer takes for true, so
    /// one that does not look at the target vouches for them all.
    ///
    /// The reader of a compilation is made by
    /// `me.supcheg.javafile.langmodel.mirror.TargetClasspaths` of
    /// `java-file-api-lang-model`; a generator calls that, not this.
    ///
    /// @param reader reads the types of the target classpath, once per shape
    /// @return the target classpath, for one compilation
    public static TargetClasspath targetClasspath(TargetReader reader) {
        return new TargetClasspath(reader);
    }

    /// A target classpath that checks nothing: every metamodel is taken for
    /// true of the code the typed layer renders, as a fact made by hand is.
    ///
    /// For where there is no compilation to check against — the tests of a
    /// generator, code rendered outside javac — and under the same audit as
    /// every other use of this class: with it, a metamodel generated against
    /// another version of a library renders code that does not compile, or
    /// that calls another overload.
    ///
    /// @return the target classpath
    public static TargetClasspath unverifiedClasspath() {
        return new TargetClasspath((shape, origin) -> TargetType.UNCHANGED);
    }

    /// Vouches for a runtime fact source (§3.8): every member `resolver`
    /// proves becomes a fact of `token`.
    ///
    /// [FactSource] is final and has no public constructor, so a source that
    /// proves everything cannot be written without this call.
    ///
    /// @param token the type whose members are looked up
    /// @param resolver proves members of `token` or fails fast
    /// @param <O> the type
    /// @return the source
    public static <O> FactSource<O> factSource(DeclaredToken<O> token, MemberResolver resolver) {
        return new FactSource<>(token, resolver);
    }
}
