plugins {
    alias(conventions.plugins.javafile.java.conventions)
    alias(conventions.plugins.javafile.publishing)
}

// The arity families (MethodRef0..12 and friends) are generated by a generator
// written on java-file-api-core and committed under src/generated/java.
// `generateArities` rewrites them; `checkArities` (part of `check`) fails when
// the committed sources are stale.
val codegen = sourceSets.create("codegen")

sourceSets.main {
    java.srcDir("src/generated/java")
}

dependencies {
    api(project(":java-file-api-core"))
    "codegenImplementation"(project(":java-file-api-core"))
}

val generatedDir = layout.projectDirectory.dir("src/generated/java")

tasks {
    val generateArities = register<JavaExec>("generateArities") {
        group = "build"
        description = "Regenerates the committed arity families"
        classpath = codegen.runtimeClasspath
        mainClass = "me.supcheg.javafile.facts.codegen.FactsCodegen"
        args(generatedDir.asFile.absolutePath, "write")
    }

    val checkArities = register<JavaExec>("checkArities") {
        group = "verification"
        description = "Checks that the committed arity families are up to date"
        classpath = codegen.runtimeClasspath
        mainClass = "me.supcheg.javafile.facts.codegen.FactsCodegen"
        args(generatedDir.asFile.absolutePath, "check")
        inputs.dir(generatedDir)
        val marker = layout.buildDirectory.file("checkArities/ok")
        outputs.file(marker)
        doLast { marker.get().asFile.writeText("ok") }
    }

    check {
        dependsOn(checkArities)
    }
}

spotless {
    java {
        targetExclude("build/**", "src/generated/**")
    }
}

testing {
    suites {
        named<JvmTestSuite>("test") {
            dependencies {
                implementation(libs.compile.testing)
            }
        }
    }
}

// The tests build the metamodels of the JDK types they need with the `@Facts` processor, which is no cycle: the
// processor is a dependency of the tests, not of the main code, and the processor jar does not depend on them.
dependencies {
    testAnnotationProcessor(project(":java-file-api-facts-processor"))
}

tasks.compileTestJava {
    options.compilerArgs.addAll(
        listOf("-Ajavafile.facts.package=me.supcheg.javafile.facts.testfacts", "-Ajavafile.facts.index=false")
    )
}
