plugins {
    alias(conventions.plugins.javafile.java.conventions)
    alias(conventions.plugins.javafile.publishing)
}

// The arity families (MethodRef0..12 and friends) are generated by a generator
// written on java-file-api-core and committed under src/generated/java.
// `generateArities` rewrites them; `checkArities` (part of `check`) fails when
// the committed sources are stale.
val codegen: SourceSet by sourceSets.creating

sourceSets.main {
    java.srcDir("src/generated/java")
}

dependencies {
    api(project(":java-file-api-core"))
    "codegenImplementation"(project(":java-file-api-core"))
}

val generatedDir = layout.projectDirectory.dir("src/generated/java")

tasks {
    val generateArities by registering(JavaExec::class) {
        group = "build"
        description = "Regenerates the committed arity families"
        classpath = codegen.runtimeClasspath
        mainClass = "me.supcheg.javafile.facts.codegen.FactsCodegen"
        args(generatedDir.asFile.absolutePath, "write")
    }

    val checkArities by registering(JavaExec::class) {
        group = "verification"
        description = "Checks that the committed arity families are up to date"
        classpath = codegen.runtimeClasspath
        mainClass = "me.supcheg.javafile.facts.codegen.FactsCodegen"
        args(generatedDir.asFile.absolutePath, "check")
        inputs.dir(generatedDir)
        val marker = layout.buildDirectory.file("checkArities/ok")
        outputs.file(marker)
        doLast { marker.get().asFile.writeText("ok") }
    }

    check {
        dependsOn(checkArities)
    }
}

spotless {
    java {
        targetExclude("build/**", "src/generated/**")
    }
}

testing {
    suites {
        named<JvmTestSuite>("test") {
            dependencies {
                implementation(libs.compile.testing)
            }
        }
    }
}
