package me.supcheg.javafile.facts.processor;

import me.supcheg.javafile.facts.meta.MetamodelFormat;
import me.supcheg.javafile.langmodel.mirror.Conformance;
import me.supcheg.javafile.langmodel.mirror.MemberFilter;
import me.supcheg.javafile.langmodel.mirror.Translation;
import me.supcheg.javafile.langmodel.mirror.TypeModel;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.util.Elements;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.lang.constant.ClassDesc;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/// Finds metamodels generated by other compilations on the classpath, and
/// publishes the ones this compilation generates (mini-spec §6).
///
/// The package of another module's metamodels is not known, so each
/// metamodel is listed in a resource named after its type, whose content is
/// the name of the metamodel class:
///
/// ```
/// META-INF/javafile/metamodel/full/java.lang.String    → com.acme.facts.java.lang.String_
/// META-INF/javafile/metamodel/token/java.lang.String   → com.acme.facts.java.lang.String_
/// ```
///
/// A metamodel found on the classpath is reused only if the fingerprint in
/// its [me.supcheg.javafile.facts.meta.GeneratedMetamodel] matches the type
/// on the current classpath — the fast path of [Conformance], which the
/// check against the target classpath starts with too: a library may ship metamodels generated
/// against another version of a type. Nor is one of another
/// [MetamodelFormat#VERSION] reused: which members have a fact is decided
/// by the format, not by the type alone. Javac finds the first resource of a
/// name on the classpath, so the first module to list a type is the one
/// asked.
final class ReuseIndex {

    /// The directory of the index resources.
    static final String ROOT = "META-INF/javafile/metamodel/";

    private static final String MARKER = "me.supcheg.javafile.facts.meta.GeneratedMetamodel";

    private final Filer filer;
    private final Elements elements;

    /// @param filer the filer of the compilation
    /// @param elements the element utilities of the compilation
    ReuseIndex(Filer filer, Elements elements) {
        this.filer = filer;
        this.elements = elements;
    }

    /// Looks for a metamodel of a type on the classpath: a full one for a
    /// full metamodel, a full or else a token-only one for a token.
    ///
    /// @param type the type
    /// @param wanted what the compilation needs of the metamodel
    /// @param models the models of the round
    /// @return the reusable metamodel, or the candidates that did not match
    Lookup find(TypeElement type, Completeness wanted, Models models) {
        String binaryName = models.binaryName(type);
        List<Completeness> directories =
                switch (wanted) {
                    case FULL -> List.of(Completeness.FULL);
                    case TOKEN -> List.of(Completeness.FULL, Completeness.TOKEN);
                };
        List<Candidate> candidates = directories.stream()
                .flatMap(directory ->
                        read(directory.path(binaryName))
                                .map(listed -> candidate(type, listed, directory, models))
                                .stream())
                .toList();
        return candidates.stream()
                .flatMap(candidate ->
                        candidate instanceof Candidate.Matching(ClassDesc metamodel, Completeness directory)
                                ? Stream.<Lookup>of(new Lookup.Reusable(metamodel, directory))
                                : Stream.empty())
                .findFirst()
                .orElseGet(() -> new Lookup.Absent(candidates.stream()
                        .flatMap(candidate -> candidate instanceof Candidate.Stale(String reason)
                                ? Stream.of(reason)
                                : Stream.empty())
                        .toList()));
    }

    /// Lists a metamodel generated by this compilation.
    ///
    /// @param completeness whether the metamodel is full or token-only
    /// @param binaryName the binary name of the type
    /// @param metamodel the metamodel class
    /// @param originating the `@Facts` the metamodel is generated for
    /// @throws IOException if the resource cannot be written
    void publish(Completeness completeness, String binaryName, ClassDesc metamodel, Element... originating)
            throws IOException {
        FileObject resource =
                filer.createResource(StandardLocation.CLASS_OUTPUT, "", completeness.path(binaryName), originating);
        try (Writer writer = resource.openWriter()) {
            writer.write(Models.binaryName(metamodel) + "\n");
        }
    }

    private Optional<String> read(String path) {
        try {
            return Optional.of(filer.getResource(StandardLocation.CLASS_PATH, "", path)
                            .getCharContent(false)
                            .toString()
                            .strip())
                    .filter(name -> !name.isEmpty());
        } catch (IOException e) {
            return Optional.empty();
        }
    }

    private Candidate candidate(TypeElement type, String listed, Completeness directory, Models models) {
        String binaryName = models.binaryName(type);
        TypeElement metamodel = elements.getTypeElement(listed);
        if (metamodel == null) {
            return new Candidate.Stale(
                    directory.path(binaryName) + " names " + listed + ", which is not on the classpath");
        }
        Optional<Map<String, Object>> marker = marker(metamodel);
        if (marker.isEmpty()) {
            return new Candidate.Stale(listed + " is not marked @GeneratedMetamodel");
        }
        Object of = marker.get().get("of");
        if (!(of instanceof DeclaredType ofType)
                || !models.binaryName((TypeElement) ofType.asElement()).equals(binaryName)) {
            return new Candidate.Stale(listed + " is the metamodel of " + of + ", not of " + binaryName);
        }
        boolean complete = Boolean.TRUE.equals(marker.get().get("complete"));
        if (directory == Completeness.FULL && !complete) {
            return new Candidate.Stale(listed + " is listed as full, but is token-only");
        }
        Object format = marker.get().get("format");
        if (!Integer.valueOf(MetamodelFormat.VERSION).equals(format)) {
            return new Candidate.Stale("metamodel " + listed + " on the classpath is of "
                    + (format == null ? "an older format" : "format " + format) + ", not of format "
                    + MetamodelFormat.VERSION + ", which this processor generates");
        }
        MemberFilter filter = complete ? MemberFilter.DECLARED_PUBLIC : MemberFilter.NONE;
        return switch (models.of(type, filter)) {
            // a metamodel is reused for the type it was generated from alone: one that still holds of a
            // changed type lacks the facts of what the type has added
            case Translation.Ok<TypeModel>(TypeModel model) ->
                marker.get().get("fingerprint") instanceof String recorded && Conformance.unchanged(recorded, model)
                        ? new Candidate.Matching(ClassDesc.of(listed), directory)
                        : new Candidate.Stale("metamodel " + listed + " on the classpath is stale against " + binaryName
                                + ": it was generated from a different " + binaryName);
            case Translation.Deferred<TypeModel>(String unresolved) ->
                new Candidate.Stale(binaryName + " mentions " + unresolved + ", which does not exist yet");
            case Translation.Unrepresentable<TypeModel>(String reason) -> new Candidate.Stale(reason);
        };
    }

    private static Optional<Map<String, Object>> marker(TypeElement metamodel) {
        return metamodel.getAnnotationMirrors().stream()
                .filter(annotation -> ((TypeElement)
                                annotation.getAnnotationType().asElement())
                        .getQualifiedName()
                        .contentEquals(MARKER))
                .findFirst()
                .map(annotation -> annotation.getElementValues().entrySet().stream()
                        .collect(Collectors.toMap(
                                entry -> entry.getKey().getSimpleName().toString(),
                                entry -> entry.getValue().getValue())));
    }

    /// Whether a metamodel has facts of the members of its type.
    enum Completeness {
        /// A token and a fact per member: `complete = true`.
        FULL("full"),
        /// A token only: `complete = false`.
        TOKEN("token");

        private final String directory;

        Completeness(String directory) {
            this.directory = directory;
        }

        /// The index resource of a type.
        ///
        /// @param binaryName the binary name of the type
        /// @return the resource path
        String path(String binaryName) {
            return ROOT + directory + "/" + binaryName;
        }
    }

    /// A metamodel on the classpath, or why there is none to reuse.
    sealed interface Lookup {

        /// A metamodel to reuse.
        ///
        /// @param metamodel the metamodel class
        /// @param completeness whether the metamodel is full or token-only
        record Reusable(ClassDesc metamodel, Completeness completeness) implements Lookup {}

        /// None to reuse.
        ///
        /// @param stale why the listed candidates do not match, empty if none is listed
        record Absent(List<String> stale) implements Lookup {}
    }

    private sealed interface Candidate {
        record Matching(ClassDesc metamodel, Completeness directory) implements Candidate {}

        record Stale(String reason) implements Candidate {}
    }
}
