package me.supcheg.javafile.typed;

import me.supcheg.javafile.JavaFile;
import me.supcheg.javafile.builder.ClassBuilder;
import me.supcheg.javafile.builder.ConstructorBuilder;
import me.supcheg.javafile.builder.EnumBuilder;
import me.supcheg.javafile.builder.FieldBuilder;
import me.supcheg.javafile.builder.InterfaceBuilder;
import me.supcheg.javafile.builder.MethodBuilder;
import me.supcheg.javafile.builder.RecordBuilder;
import me.supcheg.javafile.code.Expr;
import me.supcheg.javafile.code.Exprs;
import me.supcheg.javafile.model.Modifier;
import me.supcheg.javafile.model.Param;
import me.supcheg.javafile.type.TypeRef;
import org.jspecify.annotations.Nullable;

import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.stream.IntStream;
import java.util.stream.Stream;

/// A type being generated by a [Unit]. Members are defined completely, body
/// included, before their symbol is returned, so a body can only use members
/// defined before it; recursion through symbols is not possible.
///
/// Implicit members are available through the [TypeSym] lookups: record
/// accessors and the canonical constructor, enum constants, `values()` and
/// `valueOf(String)`, and a class's default constructor while it declares none.
///
/// ```java
/// TypeHandle circle = unit.record(CIRCLE, new Component("radius", CD_double)).implement(shape);
/// MethodSym radius = circle.method("radius", MethodTypeDesc.of(CD_double));
/// MethodSym area = circle.defineMethod("area", MethodTypeDesc.of(CD_double),
///         (code, params) -> code.return_(mul(call(this_(), radius), call(this_(), radius))));
/// ```
public final class TypeHandle extends TypeSym {
    enum Kind {
        CLASS,
        INTERFACE,
        RECORD,
        ENUM
    }

    private static final Decl DEFAULT_CTOR = new Decl(Decl.Kind.CTOR, "<init>", "()V", false);

    private final Env env;
    private final Kind kind;
    private final Object live;
    private final Consumer<Object> header;
    private final List<Component> components;
    private final List<String> constants;
    private final List<Decl> declared = new ArrayList<>();
    private final List<TypeSym> interfaces = new ArrayList<>();
    private @Nullable TypeSym superclass;
    private boolean ctorDefined;
    private boolean defaultCtorExposed;
    private boolean built;

    TypeHandle(
            Env env,
            Kind kind,
            ClassDesc desc,
            Object live,
            Consumer<Object> header,
            List<Component> components,
            List<String> constants) {
        super(desc);
        this.env = env;
        this.kind = kind;
        this.live = live;
        this.header = header;
        this.components = List.copyOf(components);
        this.constants = List.copyOf(constants);
        for (Component component : this.components) {
            declared.add(new Decl(
                    Decl.Kind.METHOD,
                    component.name(),
                    MethodTypeDesc.of(component.type()).descriptorString(),
                    false));
        }
        if (kind == Kind.RECORD) {
            MethodTypeDesc canonical = MethodTypeDesc.of(
                    ConstantDescs.CD_void,
                    this.components.stream().map(Component::type).toList());
            declared.add(new Decl(Decl.Kind.CTOR, "<init>", canonical.descriptorString(), false));
        }
        if (kind == Kind.ENUM) {
            for (String constant : this.constants) {
                declared.add(new Decl(Decl.Kind.FIELD, constant, desc.descriptorString(), true));
            }
            declared.add(new Decl(
                    Decl.Kind.METHOD,
                    "values",
                    MethodTypeDesc.of(desc.arrayType()).descriptorString(),
                    true));
            declared.add(new Decl(
                    Decl.Kind.METHOD,
                    "valueOf",
                    MethodTypeDesc.of(desc, ConstantDescs.CD_String).descriptorString(),
                    true));
        }
    }

    @Override
    public boolean isInterface() {
        return kind == Kind.INTERFACE;
    }

    @Override
    List<TypeSym> supertypes() {
        TypeSym base =
                switch (kind) {
                    case CLASS -> superclass != null ? superclass : env.type(ConstantDescs.CD_Object);
                    case INTERFACE -> env.type(ConstantDescs.CD_Object);
                    case RECORD -> env.type(ClassDesc.of("java.lang.Record"));
                    case ENUM -> env.type(ConstantDescs.CD_Enum);
                };
        return Stream.concat(Stream.of(base), interfaces.stream()).toList();
    }

    @Override
    List<Decl> declared() {
        if (kind == Kind.CLASS && !ctorDefined) {
            return Stream.concat(declared.stream(), Stream.of(DEFAULT_CTOR)).toList();
        }
        return List.copyOf(declared);
    }

    @Override
    void ctorExposed() {
        if (kind == Kind.CLASS && !ctorDefined) {
            defaultCtorExposed = true;
        }
    }

    /// Makes this class extend `superclass`.
    ///
    /// @param superclass a proven class
    /// @return this handle
    /// @throws IllegalStateException if this is not a class or already extends a class
    /// @throws IllegalArgumentException if `superclass` is an interface
    public TypeHandle extend(TypeSym superclass) {
        requireOpen();
        if (kind != Kind.CLASS || this.superclass != null) {
            throw new IllegalStateException(this + " is not a class or already has a superclass");
        }
        if (superclass.isInterface()) {
            throw new IllegalArgumentException(superclass + " is an interface");
        }
        this.superclass = superclass;
        return this;
    }

    /// Makes this type implement, or for an interface extend, `iface`.
    ///
    /// @param iface a proven interface
    /// @return this handle
    /// @throws IllegalArgumentException if `iface` is not an interface
    public TypeHandle implement(TypeSym iface) {
        requireOpen();
        if (!iface.isInterface()) {
            throw new IllegalArgumentException(iface + " is not an interface");
        }
        interfaces.add(iface);
        return this;
    }

    /// Defines a `public` instance method with parameters named `arg0`, `arg1`, ...;
    /// an interface gets a default method.
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param body populates the body
    /// @return the method symbol
    public MethodSym defineMethod(String name, MethodTypeDesc type, Body body) {
        return defineMethod(name, type, List.of(), _ -> {}, body);
    }

    /// Defines a `public` instance method; an interface gets a default method.
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param paramNames the parameter names
    /// @param body populates the body
    /// @return the method symbol
    public MethodSym defineMethod(String name, MethodTypeDesc type, List<String> paramNames, Body body) {
        return defineMethod(name, type, paramNames, _ -> {}, body);
    }

    /// Defines a `public` instance method; an interface gets a default method.
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param paramNames the parameter names
    /// @param config adds modifiers, annotations, or `throws`; must not add parameters or `static`
    /// @param body populates the body
    /// @return the method symbol
    public MethodSym defineMethod(
            String name,
            MethodTypeDesc type,
            List<String> paramNames,
            Consumer<? super MethodBuilder> config,
            Body body) {
        return define(name, type, false, paramNames, config, body);
    }

    /// Defines a `public static` method with parameters named `arg0`, `arg1`, ....
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param body populates the body
    /// @return the method symbol
    public MethodSym defineStaticMethod(String name, MethodTypeDesc type, Body body) {
        return defineStaticMethod(name, type, List.of(), _ -> {}, body);
    }

    /// Defines a `public static` method.
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param paramNames the parameter names
    /// @param body populates the body
    /// @return the method symbol
    public MethodSym defineStaticMethod(String name, MethodTypeDesc type, List<String> paramNames, Body body) {
        return defineStaticMethod(name, type, paramNames, _ -> {}, body);
    }

    /// Defines a `public static` method.
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param paramNames the parameter names
    /// @param config adds modifiers, annotations, or `throws`; must not add parameters
    /// @param body populates the body
    /// @return the method symbol
    public MethodSym defineStaticMethod(
            String name,
            MethodTypeDesc type,
            List<String> paramNames,
            Consumer<? super MethodBuilder> config,
            Body body) {
        return define(name, type, true, paramNames, config, body);
    }

    /// Defines an abstract method with parameters named `arg0`, `arg1`, ....
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @return the method symbol
    public MethodSym defineAbstractMethod(String name, MethodTypeDesc type) {
        return defineAbstractMethod(name, type, List.of());
    }

    /// Defines an abstract method in an interface, abstract class, or enum.
    ///
    /// @param name the method name
    /// @param type the erased return and parameter types
    /// @param paramNames the parameter names
    /// @return the method symbol
    /// @throws IllegalStateException if this is a record
    public MethodSym defineAbstractMethod(String name, MethodTypeDesc type, List<String> paramNames) {
        requireNew(Decl.Kind.METHOD, name, type.descriptorString());
        List<String> names = names(type, paramNames);
        Param[] params = IntStream.range(0, names.size())
                .mapToObj(i -> new Param(names.get(i), Descs.typeRef(type.parameterType(i))))
                .toArray(Param[]::new);
        Optional<TypeRef> ret = Descs.returnRef(type);
        switch (live) {
            case ClassBuilder b ->
                ret.ifPresentOrElse(
                        r -> b.withAbstractMethod(name, r, params), () -> b.withVoidAbstractMethod(name, params));
            case InterfaceBuilder b ->
                ret.ifPresentOrElse(
                        r -> b.withAbstractMethod(name, r, params), () -> b.withVoidAbstractMethod(name, params));
            case EnumBuilder b ->
                ret.ifPresentOrElse(
                        r -> b.withAbstractMethod(name, r, params), () -> b.withVoidAbstractMethod(name, params));
            default -> throw new IllegalStateException(this + " cannot declare abstract methods");
        }
        declared.add(new Decl(Decl.Kind.METHOD, name, type.descriptorString(), false));
        return new MethodSym(this, name, type, false);
    }

    /// Defines a `public` instance field of a class or enum.
    ///
    /// @param name the field name
    /// @param type the erased field type
    /// @return the field symbol
    public FieldSym defineField(String name, ClassDesc type) {
        return defineField(name, type, _ -> {});
    }

    /// Defines an instance field of a class or enum.
    ///
    /// @param name the field name
    /// @param type the erased field type
    /// @param config adds modifiers, annotations, or an initializer; must not add `static`
    /// @return the field symbol
    /// @throws IllegalStateException if this is an interface or a record
    public FieldSym defineField(String name, ClassDesc type, Consumer<? super FieldBuilder> config) {
        requireNew(Decl.Kind.FIELD, name, null);
        TypeRef ref = Descs.typeRef(type);
        switch (live) {
            case ClassBuilder b -> b.withField(name, ref, config);
            case EnumBuilder b -> b.withField(name, ref, config);
            default -> throw new IllegalStateException(this + " cannot declare instance fields");
        }
        declared.add(new Decl(Decl.Kind.FIELD, name, type.descriptorString(), false));
        return new FieldSym(this, name, type, false);
    }

    /// Defines a `public static final` field.
    ///
    /// @param name the field name
    /// @param type the erased field type
    /// @param initializer the field's value
    /// @return the field symbol
    public FieldSym defineStaticField(String name, ClassDesc type, Expr initializer) {
        requireNew(Decl.Kind.FIELD, name, null);
        TypeRef ref = Descs.typeRef(type);
        Consumer<FieldBuilder> spec = fb -> fb.withModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .withInitializer(initializer);
        switch (live) {
            case ClassBuilder b -> b.withField(name, ref, spec);
            case EnumBuilder b -> b.withField(name, ref, spec);
            case RecordBuilder b -> b.withStaticField(name, ref, initializer);
            case InterfaceBuilder b -> b.withConstant(name, ref, initializer);
            default -> throw new IllegalStateException();
        }
        declared.add(new Decl(Decl.Kind.FIELD, name, type.descriptorString(), true));
        return new FieldSym(this, name, type, true);
    }

    /// Defines a `public` constructor of a class with parameters named `arg0`, `arg1`, ....
    ///
    /// @param params the erased parameter types
    /// @param body populates the body
    /// @return the constructor symbol
    public CtorSym defineCtor(List<ClassDesc> params, Body body) {
        return defineCtor(params, List.of(), _ -> {}, body);
    }

    /// Defines a `public` constructor of a class.
    ///
    /// @param params the erased parameter types
    /// @param paramNames the parameter names
    /// @param body populates the body
    /// @return the constructor symbol
    public CtorSym defineCtor(List<ClassDesc> params, List<String> paramNames, Body body) {
        return defineCtor(params, paramNames, _ -> {}, body);
    }

    /// Defines a constructor of a class.
    ///
    /// @param params the erased parameter types
    /// @param paramNames the parameter names
    /// @param config adds modifiers, annotations, or `throws`; must not add parameters
    /// @param body populates the body
    /// @return the constructor symbol
    /// @throws IllegalStateException if this is not a class, or its default constructor was already used
    public CtorSym defineCtor(
            List<ClassDesc> params, List<String> paramNames, Consumer<? super ConstructorBuilder> config, Body body) {
        MethodTypeDesc type = MethodTypeDesc.of(ConstantDescs.CD_void, params);
        requireNew(Decl.Kind.CTOR, "<init>", type.descriptorString());
        if (!(live instanceof ClassBuilder b)) {
            throw new IllegalStateException(this + " cannot declare constructors");
        }
        if (defaultCtorExposed) {
            throw new IllegalStateException("the default constructor of " + this + " is already in use");
        }
        List<String> names = names(type, paramNames);
        b.withConstructor(cb -> {
            config.accept(cb);
            for (int i = 0; i < names.size(); i++) {
                cb.withParam(names.get(i), Descs.typeRef(type.parameterType(i)));
            }
            cb.withBody(code -> body.accept(code, params(names)));
        });
        ctorDefined = true;
        declared.add(new Decl(Decl.Kind.CTOR, "<init>", type.descriptorString(), false));
        return new CtorSym(this, type);
    }

    private MethodSym define(
            String name,
            MethodTypeDesc type,
            boolean isStatic,
            List<String> paramNames,
            Consumer<? super MethodBuilder> config,
            Body body) {
        requireNew(Decl.Kind.METHOD, name, type.descriptorString());
        List<String> names = names(type, paramNames);
        Consumer<MethodBuilder> spec = mb -> {
            mb.withModifiers(Modifier.PUBLIC);
            if (isStatic) {
                mb.withModifiers(Modifier.STATIC);
            }
            config.accept(mb);
            for (int i = 0; i < names.size(); i++) {
                mb.withParam(names.get(i), Descs.typeRef(type.parameterType(i)));
            }
            mb.withBody(code -> body.accept(code, params(names)));
        };
        Optional<TypeRef> ret = Descs.returnRef(type);
        switch (live) {
            case ClassBuilder b ->
                ret.ifPresentOrElse(r -> b.withMethod(name, r, spec), () -> b.withVoidMethod(name, spec));
            case RecordBuilder b ->
                ret.ifPresentOrElse(r -> b.withMethod(name, r, spec), () -> b.withVoidMethod(name, spec));
            case EnumBuilder b ->
                ret.ifPresentOrElse(r -> b.withMethod(name, r, spec), () -> b.withVoidMethod(name, spec));
            case InterfaceBuilder b -> {
                TypeRef r = ret.orElseThrow(() ->
                        new UnsupportedOperationException("core has no void default or static interface methods"));
                if (isStatic) {
                    b.withStaticMethod(name, r, spec);
                } else {
                    b.withDefaultMethod(name, r, spec);
                }
            }
            default -> throw new IllegalStateException();
        }
        declared.add(new Decl(Decl.Kind.METHOD, name, type.descriptorString(), isStatic));
        return new MethodSym(this, name, type, isStatic);
    }

    private static List<Expr> params(List<String> names) {
        return names.stream().<Expr>map(Exprs::field).toList();
    }

    private static List<String> names(MethodTypeDesc type, List<String> names) {
        if (names.isEmpty()) {
            return IntStream.range(0, type.parameterCount())
                    .mapToObj(i -> "arg" + i)
                    .toList();
        }
        if (names.size() != type.parameterCount()) {
            throw new IllegalArgumentException(
                    "expected " + type.parameterCount() + " parameter name(s), got " + names);
        }
        return List.copyOf(names);
    }

    private void requireNew(Decl.Kind kind, String name, @Nullable String descriptor) {
        requireOpen();
        for (Decl decl : declared) {
            if (decl.kind() == kind
                    && decl.name().equals(name)
                    && (descriptor == null || decl.descriptor().equals(descriptor))) {
                throw new IllegalArgumentException(decl.describe(desc()) + " is already defined");
            }
        }
    }

    private void requireOpen() {
        if (built) {
            throw new IllegalStateException(this + " is already built");
        }
    }

    JavaFile build() {
        built = true;
        return switch (live) {
            case ClassBuilder scratch ->
                JavaFile.class_(desc(), b -> {
                    header.accept(b);
                    if (superclass != null) {
                        b.withSuperclass(superclass.desc());
                    }
                    interfaces.forEach(i -> b.withInterface(i.desc()));
                    scratch.build().members().forEach(b);
                });
            case InterfaceBuilder scratch ->
                JavaFile.interface_(desc(), b -> {
                    header.accept(b);
                    interfaces.forEach(i -> b.withExtends(i.desc()));
                    scratch.build().members().forEach(b);
                });
            case RecordBuilder scratch ->
                JavaFile.record(desc(), b -> {
                    header.accept(b);
                    components.forEach(c -> b.withComponent(c.name(), Descs.typeRef(c.type())));
                    interfaces.forEach(i -> b.withInterface(i.desc()));
                    scratch.build().members().forEach(b);
                });
            case EnumBuilder scratch ->
                JavaFile.enum_(desc(), b -> {
                    header.accept(b);
                    constants.forEach(c -> b.withConstant(c));
                    interfaces.forEach(i -> b.withInterface(i.desc()));
                    scratch.build().members().forEach(b);
                });
            default -> throw new IllegalStateException();
        };
    }
}
